### ISSUE TITLE
[Question "AppleCpuPmCfgLock" 

### ISSUE THREAD

**Issue by Blurayx** [Pavo-IM/OC-Gen-X#55]
Thank you for creating this excellent software.

Is there a reason why you set OC Gen-X "AppleCpuPmCfgLock" to TRUE for the coffee lake?

<img width="1161" alt="Screenshot 2021-01-05 at 18 33 35" src="https://user-images.githubusercontent.com/2873112/103686036-1c10b100-4f86-11eb-837a-2534bbf0bf73.png">

https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#kernel
<img width="641" alt="Screenshot 2021-01-05 at 18 43 55" src="https://user-images.githubusercontent.com/2873112/103686222-61cd7980-4f86-11eb-980b-aee9c76675fc.png">

**Comment by Pavo-IM** [comment]
Because the app is based off the guide [Desktop Coffee Lake Guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#desktop-coffee-lake) and if you read that, in the [ Kernel -> Quirks section,](https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#kernel), it has it set to enabled
