### ISSUE TITLE
no ui in virtualbox

### ISSUE THREAD

**Issue by LokiInside** [Pavo-IM/OC-Gen-X#64]
Version 2.8.6  - 2.8.4 UI dosen't work in Oracle VM VirtualBox

Version 2.8.3 UI works in Oracle VM VirtualBox - but Generate EFI Button is off can't be pressed
Version 2.8.1 UI works in Oracle VM VirtualBox - EFI can be Generated

some error debug [messege](https://pastebin.com/raw/2dUhsud9) from UI

**Comment by Pavo-IM** [comment]
Not sure how to replicate this since I am assuming Oracle VM VirtualBox is using emulated graphics acceleration. This utilizes the Metal API to render its views, so you would have to have compatible graphics that is Metal compatible. Can you explain what part of the UI with the latest version doesn't work?

**Comment by LokiInside** [comment]
it is executed and while shuld schow UI it just closing up... error message comes later after 5 seconds

**Comment by Pavo-IM** [comment]
I am going to leave these tickets open, but it may be a while before I figure out what the actual issue is.

**Comment by Pavo-IM** [comment]
@LokiInside Can you test this one and tell me if it's still crashing.
[OC_Gen-X.zip](https://github.com/Pavo-IM/OC-Gen-X/files/6097513/OC_Gen-X.zip)

**Comment by Pavo-IM** [comment]
Fixed in latest version
