### ISSUE TITLE
OpenCore development version instead of latest stable

### ISSUE THREAD

**Issue by joostiphone** [Pavo-IM/OC-Gen-X#74]
Hello,

Everytime I'm generating a config, it seems to be the OC development (currently 068) version, instead of the release version (currently 067). The 'Preference' option is greyed out, I would assume that I would be able to choose there between development version or release version. 

I'm also using OCBuilder, so honestly, I'm a bit confused if the bug has to do with OXGENX or with OCBuilder. But...within OCBuilder I'm 100% sure I'm selecting the 'Release' channel. 

Tools versions:
OXGENX: 297
OCBuilder: 760

Best regards,
Joost

**Comment by Pavo-IM** [comment]
OC Gen-X will only generate a 0.6.7 release version of OpenCore. OCBuilder does a git clone of the current committed version of whatever is on OpenCorePkg's git repo, which at the time of writing this reply is 0.6.8. OCBuilder you can create a "Release" or "Debug" version of that schema. What you are referring to as "OC Development" is similar to nightly build versions.

**Comment by joostiphone** [comment]
My bad, with development version I meant when it's not yet a release on:
https://github.com/acidanthera/OpenCorePkg/releases 

If you look at OpenCorePkg's git hub repo and go to /releases, then 067 is the latest, correct? I thought that OCBuilder would get that latest version (067 at the moment of writing). 

Is there a reason why OC Gen-X and OCBuilder don't generate output for the same OpenCore version? This is confusing to me (pls note I'm not a dev, so I'm sure there is a completely valid reason for this).

**Comment by Pavo-IM** [comment]
> If you look at OpenCorePkg's git hub repo and go to /releases, then 067 is the latest, correct? I thought that OCBuilder would get that latest version (067 at the moment of writing).

0.6.7 is the latest "Release" version but you can either download the non-debug "Release" or debug "Debug" version. OCBuilder does a git clone of the repo of the current head of that repo, so whatever naming scheme that version is using is what OCBuilder will compile during its building phase.

> Is there a reason why OC Gen-X and OCBuilder don't generate output for the same OpenCore version? This is confusing to me (pls note I'm not a dev, so I'm sure there is a completely valid reason for this).
OC Gen-X is an app that only provides the current non-debug "Release" version, which is the same from https://github.com/acidanthera/OpenCorePkg/releases, OCBuilder was made before I came up with the idea of creating an app that was based off specific system types. Plus writing two apps gave me more opportunity to teach myself Swift programming.

**Comment by joostiphone** [comment]
Okay. This explains why you developed 2 apps, thanks for that explanation. 

If I want to upgrade my OpenCore EFI, I use OCBuilder to get all the EFI files + kexts etc. And I use OC Gen-X to generate the config file, which I then copy to the OCBuilder-generated folder. After that I apply my own tweaks to the EFI with OpenCoreConfigurator.

It would perhaps make more sense if OCBuilder would get the 'create a config' functionality which OC Gen-X is currently providing. Then you would have 1 app do all these steps in 1 go (for your system specifically). Af(terwhich you would still need to apply own tweaks to the EFI which can be system/user specific).

Does this make sense?

**Comment by Pavo-IM** [comment]
The intent or purpose of each app are different. OCBuilder's intent was to have an app to compile the latest commits of the repo and all repos of selected kext, this was before Github introduced the Actions feature that auto compiles that on the repo itself. OC Gen-X's intent is to have an app that generates a pre-defined config and a EFI folder folder that is based off the user's selected system type.

The reason I never or will never add that generated config feature set to OCBuilder is because the OpenCorePkg repo is constantly being updated or changed repo and trying to keep up with its changes will become a full-time job. I only write these apps to fulfill gaps in the hackintosh community and to continue teaching myself how to write Swift programs. 

Normal users should only be using the official release of OpenCore ie... OC Gen-X and more advanced user can use OCBuilder to test out new features that OpenCore has added to the "development" version.  They are not meant to be used with each other.  As for as OpenCoreConfigurator, that is not an app I wrote or participated in as a developer. Yes I could add certain features to OC Get-X that it supports, which I do plan on doing, but currently do not have the knowledge in the Swift programming language to implement those features, hence the reason why I am continuously teaching myself Swift programming.

**Comment by joostiphone** [comment]
Thanks for your comments! You're doing a great job imo. I need to find a proper workflow to update my OpenCore EFI using OC Gen-X, without using OCBuilder then.  

Thank again.

**Comment by Pavo-IM** [comment]
The workflow would be.... Wait until OpenCorePkg devs do their release cycle, which is the first Monday of the month. OC Gen-X will have updated binaries the same day that is published from the OpenCorePkg devs.
