### ISSUE TITLE
Great piece of software..Some thoughts for future builds...

### ISSUE THREAD

**Issue by aniuks33** [Pavo-IM/OC-Gen-X#8]
Great idea to make Opencore even easier to setup
Some thoughts after testing it today:

- WhateverGreen.kext could be added to essential list
-Required aml's (or .dsl files to compile) could be added to EFI Folder depending on system type (ex. Skylake has two SSDTs to be added to ACPI folder: PLUG and EC-USBX)
-OpenCanopy.efi is missing from drivers folder.
-SMBIOS section could have generate button to auto-generate serial numbers after selecting SMBIOS type, example iMac17,1

**Comment by Pavo-IM** [comment]
Thanks for the suggestions but here is the reason I am not adding any of the suggestions you are asking for.

> WhateverGreen.kext could be added to essential list
- WhateverGreen is not needed to boot on all systems types, if someone needs it, they can enable it themselves. But most do not need it at all.

> Required aml's (or .dsl files to compile) could be added to EFI Folder depending on system type (ex. Skylake has two SSDTs to be added to ACPI folder: PLUG and EC-USBX)
- SSDTs are not being added simply because there is thousands of ways of doing them and I can not guarentee the user has iasl installed on their system, I will not include it my app because of other reasons.

> OpenCanopy.efi is missing from drivers folder.
- OpenCanopy.efi again is not needed in order to boot, the default setting in Sample.plist that comes with OpenCore release uses `Builtin` option which mean OpenCanopy.efi is not needed. 
 

> SMBIOS section could have generate button to auto-generate serial numbers after selecting SMBIOS type, example iMac17,1
- SMBIOS generation, I actually thought about adding that feature but with all the stink going around right now with copyrights and such I decided against it because who knows what issues it could cause.
